// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-obras.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-obras.ts
var list_obras_default = defineTool({
  name: "list_obras",
  title: "Listar obras",
  description: "Lista as obras (centros de custo) vis\xEDveis para o usu\xE1rio autenticado, com busca opcional por nome ou c\xF3digo.",
  inputSchema: {
    busca: z.string().trim().optional().describe("Filtra por nome ou c\xF3digo da obra."),
    limite: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de obras (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, limite }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("obras").select("id, codigo, nome, status, cliente_id, centro_custo_totvs, valor_contrato").order("codigo").limit(limite ?? 50);
    if (busca) query = query.or(`nome.ilike.%${busca}%,codigo.ilike.%${busca}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { obras: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-obra.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_obra_default = defineTool2({
  name: "get_obra",
  title: "Detalhar obra",
  description: "Retorna os dados completos de uma obra pelo seu id (UUID).",
  inputSchema: { obra_id: z2.string().uuid().describe("UUID da obra.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ obra_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("obras").select("*").eq("id", obra_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Obra n\xE3o encontrada" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { obra: data }
    };
  }
});

// src/lib/mcp/tools/list-cronograma-obra.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_cronograma_obra_default = defineTool3({
  name: "list_cronograma_obra",
  title: "Listar cronograma da obra",
  description: "Lista os itens de cronograma de uma obra, com datas, avan\xE7o e marca\xE7\xE3o de caminho cr\xEDtico.",
  inputSchema: {
    obra_id: z3.string().uuid().describe("UUID da obra."),
    apenas_criticos: z3.boolean().optional().describe("Retorna apenas itens do caminho cr\xEDtico."),
    limite: z3.number().int().min(1).max(500).optional().describe("M\xE1ximo de itens (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ obra_id, apenas_criticos, limite }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cronograma_itens").select("id, descricao, data_inicio, data_fim, percentual_concluido, critico, folga_dias").eq("obra_id", obra_id).order("data_inicio").limit(limite ?? 100);
    if (apenas_criticos) query = query.eq("critico", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { itens: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-medicoes-obra.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_medicoes_obra_default = defineTool4({
  name: "list_medicoes_obra",
  title: "Listar medi\xE7\xF5es da obra",
  description: "Lista as medi\xE7\xF5es (boletins de medi\xE7\xE3o) registradas para uma obra.",
  inputSchema: {
    obra_id: z4.string().uuid().describe("UUID da obra."),
    limite: z4.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ obra_id, limite }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("medicoes").select("*").eq("obra_id", obra_id).limit(limite ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { medicoes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-oportunidades.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_oportunidades_default = defineTool5({
  name: "list_oportunidades",
  title: "Listar oportunidades (CRM)",
  description: "Lista as oportunidades do CRM vis\xEDveis para o usu\xE1rio autenticado, com filtro opcional por etapa/status.",
  inputSchema: {
    status: z5.string().trim().optional().describe("Etapa/status da oportunidade."),
    busca: z5.string().trim().optional().describe("Filtra pelo t\xEDtulo da oportunidade."),
    limite: z5.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, busca, limite }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("oportunidades").select("*").limit(limite ?? 50);
    if (status) query = query.eq("status", status);
    if (busca) query = query.ilike("titulo", `%${busca}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { oportunidades: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ftqmgcxhevbwcddtkhrq";
var mcp_default = defineMcp({
  name: "erp-jogab",
  title: "ERP-JOGAB",
  version: "0.1.0",
  instructions: "Ferramentas do ERP-JOGAB (gest\xE3o de obras). Use `list_obras` para localizar uma obra e obter seu id, depois `get_obra`, `list_cronograma_obra` ou `list_medicoes_obra` para detalhes. `list_oportunidades` consulta o funil de vendas (CRM). Todas as consultas respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_obras_default, get_obra_default, list_cronograma_obra_default, list_medicoes_obra_default, list_oportunidades_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
